# Generated by Django 3.0.3 on 2020-02-16 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(whitelist='올바른 이메일 주소를 입력해주세요.')], verbose_name='이메일(ID)')),
                ('student_id', models.CharField(max_length=100, null=True, verbose_name='학번')),
                ('department', models.CharField(max_length=150, null=True, verbose_name='전공')),
                ('department2', models.CharField(blank=True, max_length=150, null=True, verbose_name='이중/융합전공')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='이름')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='연락처')),
                ('sign_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField(max_length=2000, verbose_name='지원동기 (1000자 내외)')),
                ('q2', models.TextField(max_length=2000, verbose_name='향후 5년 계획과, 10년 후의 나의 모습을 이야기해 주세요. (1000자 내외)')),
                ('q3', models.TextField(max_length=2000, verbose_name='인생에서 가장 도전적이었던 경험과, 그 경험을 통해 얻은 것과 잃은 것은 무엇인가요? (1000자 내외)')),
                ('q4', models.TextField(max_length=2000, verbose_name='만들고 싶은 서비스와 그 계기 및 이유를 설명해 주세요. (1000자 내외)')),
                ('q5', models.TextField(max_length=2000, verbose_name='멋사 활동을 통해 얻고 싶은 것과 자신이 멋사에 기여할 수 있는 것은 무엇인지 이야기해 주세요. (1000자 내외)')),
                ('q6', models.TextField(blank=True, max_length=400, null=True, verbose_name='멋사외에 활동했던, 혹은 활동 예정인 동아리나 학회가 있으면 간략하게 적어주세요.(없으면 생략가능)')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
